export default actionTypes = {
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
  SHOW_HOME: "SHOW_HOME",
  SAVE_API_TOKEN: "SAVE_API_TOKEN",
  USER_DETAILS: "USER_DETAILS",
  SET_LAT_LONG: "SET_LAT_LONG",
};
